#!/usr/bin/env bash


case "$(xset -q|grep LED| awk '{ print $10 }')" in
  "00000002") KBD="En" ;;
  "00001002") KBD="Ru" ;;
  "00000000") KBD="En" ;;
  "00001000") KBD="Ru" ;;

  "00000003") KBD="En (CL)" ;;
  "00001003") KBD="Ru (CL)" ;;
  "00000001") KBD="En (CL)" ;;
  "00001001") KBD="Ru (CL)" ;;

  *) KBD="unknown" ;;
esac

echo $KBD

